# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Today i learned
email1: frederiksvendsen111@hotmail.com
email2: frederik.n.svendsen@jp.dk
description: > # this means to ignore newlines until "baseurl:"
  Today i learned - Frederik Nygaard Svendsen
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  frederiknygaardsvendsen
facebook_username:  frederik.n.svendsen

# Build settings
markdown: kramdown
